// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ4I2eTUx-jmfFpzj06aaAh8O5T0pc_tE',
    appId: '1:149353407539:web:a7e9b57f25489b37d06f46',
    messagingSenderId: '149353407539',
    projectId: 'modern-login-ui-auth',
    authDomain: 'modern-login-ui-auth.firebaseapp.com',
    storageBucket: 'modern-login-ui-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn2h3B-1Xclu4PrLnP7JLnnin6Zat6c_k',
    appId: '1:149353407539:android:c230e55e89b93ea5d06f46',
    messagingSenderId: '149353407539',
    projectId: 'modern-login-ui-auth',
    storageBucket: 'modern-login-ui-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmYSonjwkALJseodGH7GqTjTXj3-bjtjU',
    appId: '1:149353407539:ios:a5d74f326087d76ed06f46',
    messagingSenderId: '149353407539',
    projectId: 'modern-login-ui-auth',
    storageBucket: 'modern-login-ui-auth.appspot.com',
    iosBundleId: 'com.example.modernLoginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmYSonjwkALJseodGH7GqTjTXj3-bjtjU',
    appId: '1:149353407539:ios:a5d74f326087d76ed06f46',
    messagingSenderId: '149353407539',
    projectId: 'modern-login-ui-auth',
    storageBucket: 'modern-login-ui-auth.appspot.com',
    iosBundleId: 'com.example.modernLoginUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ4I2eTUx-jmfFpzj06aaAh8O5T0pc_tE',
    appId: '1:149353407539:web:c62ee6f37d3c82f9d06f46',
    messagingSenderId: '149353407539',
    projectId: 'modern-login-ui-auth',
    authDomain: 'modern-login-ui-auth.firebaseapp.com',
    storageBucket: 'modern-login-ui-auth.appspot.com',
  );
}
